### PR TITLE
Support for CDI 3+ . fixes #509

### LINKED ISSUE #509: Update CDI integration to use Jakarta EE after big bang.
Once we have more adoptions and vendors that use Jakarta EE, how about updating to CDI 3.0 or higher?

Does it make sense?

@rdebusscher 

Source code: https://github.com/microstream-one/microstream/tree/master/integrations/cdi

### PR DESCRIPTION
**Pull request by rdebusscher**
jakarta namespace version of the CDI integration.

### CODE REVIEW

**Comment by otaviojava** [comment]
@rdebusscher could you isolate the configuration in a module?

I will create a Jakarta-Data integration; thus, I will use the same configuration.

Also, please, provide one way to register the type handle.

**Comment by rdebusscher** [comment]
@otaviojava 

Not sure what you exactly need, is it just the cache part that you do not need? Can you just use this module as is for the moment?

Also, there will be no release of MicroStream 8 (listen here https://youtu.be/T5cJTF3zkuU?t=807) but only the Eclipse project release later on.  So it might be easier that you copy what is needed for the demo at the moment so that we can do a proper solution when we have the Eclipse repositories after the creation review is finished.

**Review by fh-ms — CHANGES_REQUESTED** [review]
A link to cdi.adoc is missing in nav.adoc

**Comment by rdebusscher** [comment]
> A link to cdi.adoc is missing in nav.adoc

I see the link present in the `nav.adoc` file. It is present in the current version of master and this PR does not make a change to the `nav.adoc`

**Comment by fh-ms** [comment]
I see, my fault, the cdi.adoc was updated, not added.

**Review by fh-ms — APPROVED** [review]

**Pull request merged**
