### PR TITLE
Javadoc Update

### PR DESCRIPTION
**Pull request by fh-ms**
Fixed javadoc warnings

### CODE REVIEW

**Review by zdenek-jonas — APPROVED** [review]
Ok, I just add a check for pull_reuqest and fix whitespace in pom.xml.

**Comment by zdenek-jonas** [comment]
Please add:
src/main/java/one/microstream/persistence/binary/types/Binary.java:313
src/main/java/one/microstream/persistence/binary/internal/CustomBinaryHandler.java:737
src/main/java/one/microstream/storage/types/StorageEntity.java:256
src/main/java/one/microstream/storage/types/StorageEntityCache.java:725 and 904
src/main/java/one/microstream/storage/types/StorageEntityInitializer.java:174
src/main/java/one/microstream/storage/types/StorageEntityMarkMonitor.java:755
src/main/java/one/microstream/storage/types/StorageTaskBroker.java:372
src/main/java/one/microstream/storage/restadapter/types/ViewerObjectDescriptionCreator.java:152  165 255 279 292
src/main/java/one/microstream/chars/XChars.java:2579

**Review by zdenek-jonas — CHANGES_REQUESTED** [review]
There are some failed Javadoc, which is not found with the plugin, but due to code analysis in IDE.

**Comment by fh-ms** [comment]
Fixed IDE warnings

**Review by zdenek-jonas — APPROVED** [review]

**Pull request merged**
